spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
  application:
    name: gateway

eureka:
  client:
    fetch-registry: true

server:
  servlet:
    session:
      persistent: false
logging:
  level:
    org.springframework.cloud.gateway: DEBUG


